name: Update readme with latest YouTube videos
on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:
permissions:
  actions: write
  contents: write
jobs:
  update-readme-with-videos:
    name: ðŸ”„ Update this repo's README with latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: update readme with YouTube videos
        uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCc79YC0GBcP6ugYag80fuPA
